AllCops:
  NewCops: enable
  Exclude:
    - spec/spec_helper.rb
    - spec/rails_helper.rb
    - db/**/*
    - docs/**/*
    - config/**/*
    - bin/**/*
    - vendor/bundle/**/*
    - Gemfile
    - Rakefile
    - config.ru

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/PredicateName:
  Exclude:
    - app/serializers/**/*

Rails/HasManyOrHasOneDependent:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

RSpec/EmptyExampleGroup:
  Enabled: false

require:
  - rubocop-rails
  - rubocop-rspec
